[package]
name = "oxide-wdns"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false
incremental = false
overflow-checks = false

[[bin]]
name = "owdns"
path = "src/bin/owdns.rs"

[[bin]]
name = "owdns-cli"
path = "src/bin/owdns_cli.rs"

[dependencies]
# TODO: Add dependencies here as needed
# Server dependencies might include: axum, tokio, tracing, serde, serde_yaml, thiserror, moka, trust-dns-proto, trust-dns-resolver, prometheus, etc.
# Client dependencies might include: reqwest, clap, tokio, trust-dns-proto, serde_json, thiserror, etc.
