[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=/NODEFAULTLIB:libcmt",
]

[target.x86_64-pc-windows-gnu]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-args=-static-libgcc -static-libstdc++",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-static",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-feature=+crt-static",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-feature=+crt-static",
]

[build]
rustflags = ["-C", "prefer-dynamic=no"]