apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxide-wdns
  labels:
    app: oxide-wdns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oxide-wdns
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: oxide-wdns
    spec:
      containers:
        - name: oxide-wdns
          image: your-registry/oxide-wdns:latest # 替换为您的镜像仓库和标签
          imagePullPolicy: Always
          ports:
            - containerPort: 3053
              name: dns-http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          livenessProbe:
            httpGet:
              path: /health
              port: 3053
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3053
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
      volumes:
        - name: config-volume
          configMap:
            name: oxide-wdns-config
