apiVersion: v1
kind: Service
metadata:
  name: oxide-wdns
  labels:
    app: oxide-wdns
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3053"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 3053
      targetPort: 3053
      protocol: TCP
      name: dns-http
  selector:
    app: oxide-wdns
